### PR TITLE
Changed source/_data/pub.bib

### PR DESCRIPTION
**Pull request by tuoping**
1. changed infos of some papers
2. sorted by year and author

### CODE REVIEW

**Comment by tuoping** [comment]
How did you generate the files in source/papers? What should I do about it?

**Comment by njzjz** [comment]
> How did you generate the files in source/papers? What should I do about it? @njzjz 

I wrote a script to generate that...

**Comment by tuoping** [comment]
Just a suggestion, maybe you can put your script in workflow?

**Comment by njzjz** [comment]
Maybe it's a better way to update my plugin... I'll take a look at it when I have the time.

**Comment by njzjz** [comment]
> Just a suggestion, maybe you can put your script in workflow?

Implement in 4be690da1acbc3cd015f4150e8f257048538f644. You can directly put citations in https://github.com/deepmodeling/blog/blob/master/source/_data/reviews.bib.

**Pull request merged**
